# Generated by Django 4.2.4 on 2023-08-16 10:15

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryapproval",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="UUID"),
        ),
        migrations.AlterField(
            model_name="entryapproval",
            name="source",
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="approval", to="content.entry"
            ),
        ),
    ]
